---
root: true

parser: '@typescript-eslint/parser'
extends:
  - plugin:react/recommended
  - plugin:prettier/recommended
  - airbnb-typescript
  - airbnb/hooks
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint

settings:
  react:
    version: detect

env:
  browser: true
  node: true
  es6: true

plugins:
  - '@typescript-eslint'
  - prettier
  - react
  - react-hooks

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  project: ./tsconfig.json
  sourceType: module

rules:
  react/prop-types: off
  '@typescript-eslint/explicit-function-return-type': off
  import/extensions:
    - error
    - ignorePackages
    - '': never
      js: never
      jsx: never
      ts: never
      tsx: never
      mjs: never

overrides:
  - files:
      - '*.js'
    rules:
      '@typescript-eslint/no-var-requires': off

ignorePatterns:
  - gatsby-*.js
  - generated/*
