[build]
  functions = "./netlify/functions"

[context.production.environment]
  PL_SITE_URL = "https://patricklim.fr"

[context.deploy-preview.environment]
  PL_SITE_URL = "https://deploy-preview-1--patricklim.netlify.app"
  